window:
	clang++ *.cpp ../glad/src/glad.c -o main -I ../glad/include -lSDL2main -lSDL2 -lglfw3 -w

linux:
	clang++ *.cpp ../glad/src/glad.c -o main -I ../glad/include -lSDL2 -lglfw -w

macbrew:
	clang++ *.cpp ../glad/src/glad.c -o main -I ../glad/include -I /opt/homebrew/include -L /opt/homebrew/lib -lSDL2 -lglfw -w

dummy:
