linux:
	clang++ main.cpp glad/src/gl.c -o main -I glad/include -lSDL2 -lSDL2_ttf -std=c++11 -w

linux2:
	clang++ main2.cpp -o main2 -lSDL2 -lSDL2_ttf -lGL -lGLU -std=c++11 -w

mingw2:
	clang++ main2.cpp -o main2 -lSDL2main -lSDL2 -lSDL2_ttf -lopengl32 -std=c++11 -w