linux:
	clang++ main.cpp script/*.cpp ../glad/src/glad.c -o main -I ../glad/include -lSDL2 -lglfw -w

macbrew:
	clang++ main.cpp script/*.cpp ../glad/src/glad.c -o main -I ../glad/include -I /opt/homebrew/include -L /opt/homebrew/lib -lSDL2 -lglfw -w

dummy:
