windows-mingw:
	clang++ main.cpp script/*.cpp -o main -lSDL2main -lSDL2 -w

macbrew:
	clang++ main.cpp script/*.cpp -o main -lSDL2 -w

termux:
	clang++ main.cpp script/*.cpp -o main -lSDL2 -w -D SCALED=0

linux:
	clang++ main.cpp script/*.cpp -o main -lSDL2 -w -D SCALED=1

dummy:
	